### ISSUE TITLE
UI for containers screen

### ISSUE THREAD

**Issue by anshul2401** [bigpanther/shipanther#104]
![WhatsApp Image 2020-12-02 at 10 27 48 PM](https://user-images.githubusercontent.com/55911213/100905497-26a2db00-34ee-11eb-9069-5d3d41656444.jpeg)

**Comment by anshul2401** [comment]
What else options can we give in sorting other than incoming and outgoing?

**Comment by anshul2401** [comment]
Sorting should be according to lfd or Reservation time?

**Comment by harsimranmaan** [comment]
Thanks @anshul2401 . I'll also try to iterate over the ux design and then we can do an implementation

**Comment by schima** [comment]
Either show all the items in the list and hide the keyboard, as users first reaction would be to make selection from the item list. OR do not show any items from the list, and let user type in the name and then show the filtered list. 

issue is valid and tested

**Comment by harsimranmaan** [comment]
I think this can be covered in the overall ux refresh
