### ISSUE TITLE
Customer cannot be attached in orders

### ISSUE THREAD

**Issue by schima** [bigpanther/shipanther#113]
-After login to app, go to burger menu>Orders. 
-click edit on any order. 
-Click select Customer. 
-Select any customer from choices offered. 

Observed. It does not get added to the order. The field remains empty.

**Comment by harsimranmaan** [comment]
I think this might be a duplicate of #80

**Comment by harsimranmaan** [comment]
The field is assigned but the user has not visual indication

**Comment by harsimranmaan** [comment]
I think this is a case of customer case not shown on the order list page.

**Comment by schima** [comment]
Thanks. looking forward to getting this fixed in newer version
