### ISSUE TITLE
iOS- New customer cannot be created, it gives blank screen

### ISSUE THREAD

**Issue by schima** [bigpanther/shipanther#115]
-After login,  open customers from left side burger menu. 
-Click the green button to add new customer. 

Observed. Blank screen. User cannot do anything. Only way out is to swipe back from left corner or kill the app and restart.

**Comment by harsimranmaan** [comment]
I think the blank screen is a generic issue happening on ios.

**Comment by harsimranmaan** [comment]
Maybe related to https://github.com/flutter/flutter/issues/36247

**Comment by harsimranmaan** [comment]
I think we should prioritize #85 to get more insights into running apps
