### ISSUE TITLE
Add a link to a wiki page with app screenshots

### ISSUE THREAD

**Issue by harsimranmaan** [bigpanther/shipanther#182]
This would help someone new get an idea about the app. This could also include info on things like how to join the beta program. Later when the app is published publicly, it can include links to the play and app store links.

**Comment by harsimranmaan** [comment]
It would also be nice to have some gif which show app workflows

**Comment by schima** [comment]
Create a centralized folder to create public wikis. Then I can add a wiki there.

**Comment by schima** [comment]
Will add wiki to this area
https://github.com/bigpanther/shipanther/wiki

**Comment by schima** [comment]
will write wiki on this tmrw.

**Comment by schima** [comment]
> Will add wiki to this area
> https://github.com/bigpanther/shipanther/wiki

done at https://github.com/bigpanther/shipanther/wiki/Shipanther-iOS-mobile-application

**Comment by harsimranmaan** [comment]
Perfect. Thanks
