### ISSUE TITLE
Add the default app icon

### ISSUE THREAD

**Issue by harsimranmaan** [bigpanther/shipanther#2]
The current application icon is the default flutter icon. A custom shipanther icon should be created and added

**Comment by nicoletamaan** [comment]
![Untitled design (1)](https://user-images.githubusercontent.com/74070320/98431444-33a4e980-206a-11eb-820c-6e8c5358a916.png)
You can use this

**Comment by nicoletamaan** [comment]
![Shipanther](https://user-images.githubusercontent.com/74070320/98431479-b332b880-206a-11eb-926f-38cc878e7b8f.png)
