### ISSUE TITLE
Create a new logo for the app

### ISSUE THREAD

**Issue by nicoletamaan** [bigpanther/shipanther#239]

**Comment by martareg** [comment]
Logo proposal.
![Logo Footprint](https://user-images.githubusercontent.com/77104115/104640113-79081780-56a8-11eb-9f1a-f71fbdba44a8.png)

**Comment by martareg** [comment]
I am sending a few logo version proposals. Let me know what you think. Do you like any of the logos or should I change something? Is PNG ok, or do you need other format?   
![LogoShipanther0](https://user-images.githubusercontent.com/77104115/105345100-1b158b80-5be4-11eb-8725-8c4c0a200a25.png)  
![Logo Shipanther1](https://user-images.githubusercontent.com/77104115/105349015-641c0e80-5be9-11eb-8df7-e167c9d98637.png)  
![LogoShipanther2](https://user-images.githubusercontent.com/77104115/105349704-65017000-5bea-11eb-897b-f08b6225cc51.png)  
![LogoShipanther3](https://user-images.githubusercontent.com/77104115/105350142-fb359600-5bea-11eb-84d7-6a0da7c50fd8.png)
