### ISSUE TITLE
About us is not working

### ISSUE THREAD

**Issue by nicoletamaan** [bigpanther/shipanther#243]

**Comment by schima** [comment]
Seems working for me in the latest build.

**Comment by harsimranmaan** [comment]
This seems android specific

**Comment by harsimranmaan** [comment]
This is likely fixed already. would test and close.

**Comment by harsimranmaan** [comment]
Does not work in Android 10. Runs fine when using ios or another android version. Might need `android:requestLegacyExternalStorage="true"`

**Comment by harsimranmaan** [comment]
Relates https://github.com/flutter/flutter/issues/62669
