### ISSUE TITLE
Registration & Sign in Mockups

### ISSUE THREAD

**Issue by martareg** [bigpanther/shipanther#249]
Initial mockups let me know what you think.

Screen nr 3.  Check your inbox' button opens email app. When user clicks on activation link he is redirected to application home page already logged in. Also please let me know if colors are fin.

![Sing in](https://user-images.githubusercontent.com/77104115/104050029-3f399b80-51e6-11eb-8af5-dc96ae79248e.png)

![Sing up](https://user-images.githubusercontent.com/77104115/104050050-452f7c80-51e6-11eb-99ea-a0a1af3cb473.png)

![Sing up 2](https://user-images.githubusercontent.com/77104115/104050062-495b9a00-51e6-11eb-9ec4-b799f28a834e.png)

**Comment by nicoletamaan** [comment]
this looks very good. I like the colors 😊

**Comment by harsimranmaan** [comment]
Thanks @martareg. These look amazing. I'll work to incorporate these into the app. Do you think it would be possible to use the same set of button colors for dark mode? You can check the current dark theme on the app by setting your phone to use the dark theme temporarily.

**Comment by martareg** [comment]
I made two versions with purple, the only difference is the type of inputs. I had to change the colors from the light version because it was too dark in this case. I also made a version in orange because it also looks interesting, but it depends on you what you prefer :) Do  you want the application to have light and dark modes, or only dark?
![Sing in Dark – 3](https://user-images.githubusercontent.com/77104115/104091958-3944c880-5281-11eb-85b0-87552a780229.png)
![Sing in Dark – 4](https://user-images.githubusercontent.com/77104115/104091960-3ba72280-5281-11eb-9e4e-fdbc47ddfabf.png)
![Sing up -1](https://user-images.githubusercontent.com/77104115/104091962-3cd84f80-5281-11eb-90ff-f601fc20ae7c.png)
![Sing in Dark](https://user-images.githubusercontent.com/77104115/104091976-56799700-5281-11eb-97f3-5a67cf3e86dd.png)
![Sing up-1](https://user-images.githubusercontent.com/77104115/104091981-58dbf100-5281-11eb-9098-ed6515cf385f.png)
![Sing in Dark – 6](https://user-images.githubusercontent.com/77104115/104091991-642f1c80-5281-11eb-99f2-20267c45bfa1.png)
![Sing in Dark – 7](https://user-images.githubusercontent.com/77104115/104091996-66917680-5281-11eb-8389-ec708b358fb7.png)
![Sing up 2 – 1](https://user-images.githubusercontent.com/77104115/104092001-685b3a00-5281-11eb-9f10-388e2240457e.png)

**Comment by harsimranmaan** [comment]
I like the purple more than orange

**Comment by harsimranmaan** [comment]
We'll support both light and dark themes

**Comment by martareg** [comment]
I drew a new sent-mail icon so that it could be used in the application. Earlier mockups had a free icon, but it wasn't drawn by me.   
![Logo Send-email](https://user-images.githubusercontent.com/77104115/104807806-20d53080-57e2-11eb-8dd9-24c58519cf06.png)

**Comment by harsimranmaan** [comment]
Thanks Marta. We can reuse icons open source icons with proper attributions. We are already using the material icons set that come with flutter and the icons from https://materialdesignicons.com/ which can be previewed [here](https://pictogrammers.github.io/@mdi/font/5.4.55/) . I'd also encourage to submit your work at https://github.com/templarian/MaterialDesign if you'd like to make it accessible to everyone.
