### ISSUE TITLE
iOS 14.4. Photo upload from driver did not work.

### ISSUE THREAD

**Issue by schima** [bigpanther/shipanther#296]
-Login as driver user. 
-Ensure driver has at least 1 entry under pending. 
-click on entry and click delivered. User will see camera enabled to click photo. 
-take a photo and select "use photo" 

Observed: photo upload does not work. 

Expected: upload should work and transaction completed.

**Comment by harsimranmaan** [comment]
This is caused by the missing directory for uploads in the backend. Would be fixed server side.

**Comment by schima** [comment]
It seems fixed now.

**Comment by harsimranmaan** [comment]
This was caused by missing claims assignment for the users, would be fixed server side.

**Comment by harsimranmaan** [comment]
Tracked in https://github.com/bigpanther/trober/issues/105
