### ISSUE TITLE
Assigning shipment to driver did not send iOS 14.4 notifications.

### ISSUE THREAD

**Issue by schima** [bigpanther/shipanther#300]
App version 0.11
iOS version 14.4

-Ensure iOS notification for app are fully all options enabled. 
-login to the app as driver user. 
-assign a pickup to this driver from another login from another machine. 

Observed: driver user did not get any iOS notifications. 

Expected: iOS user notifications should have come thru. User should have got notification on locked or unlocked screen.

**Comment by harsimranmaan** [comment]
This was caused by missing claims assignment for the users, would be fixed server side.
