### ISSUE TITLE
Rejecting the delivery crashes the app

### ISSUE THREAD

**Issue by schima** [bigpanther/shipanther#303]
iOS app 0.11
Driver login
Logged in user : info+d

Steps. 
-Have at least 1 delivery assigned to the driver. 
-driver reject the delivery. 

Observed: user gets unhandled error and app never recovers. 

Expected: app should not crash. Error should be handled gracefully. ![image](https://user-images.githubusercontent.com/20378193/113350012-b9f9ea80-92ed-11eb-82fb-f5b2c0390d4f.png)

**Comment by harsimranmaan** [comment]
Requires https://github.com/bigpanther/trober/issues/100

**Comment by harsimranmaan** [comment]
As a workaround, the user can click on an item from the burger menu when the app spins indefinitely.
