### ISSUE TITLE
Get user's preferred name on registration

### ISSUE THREAD

**Issue by harsimranmaan** [bigpanther/shipanther#57]

**Comment by harsimranmaan** [comment]
See https://firebase.google.com/docs/auth/web/manage-users#update_a_users_profile

**Comment by anshul2401** [comment]
I have to make another input field for taking name of the user?

**Comment by harsimranmaan** [comment]
Yes, another fields to get the user's preferred name should be sufficient. This data should be then set on the user's firebase profile

**Comment by harsimranmaan** [comment]
Implemented in #67
