### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by anshul2401** [bigpanther/shipanther#97]
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
 lib\main.dart

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processProdDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\Anshul\Desktop\shipanther\android\app\google-services.json
  C:\Users\Anshul\Desktop\shipanther\android\app\src\prod\google-services.json
  C:\Users\Anshul\Desktop\shipanther\android\app\src\debug\google-services.json
  C:\Users\Anshul\Desktop\shipanther\android\app\src\prodDebug\google-services.json
  C:\Users\Anshul\Desktop\shipanther\android\app\src\prod\debug\google-services.json
  C:\Users\Anshul\Desktop\shipanther\android\app\src\debug\prod\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12m 44s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by harsimranmaan** [comment]
Use `--flavor dev` when running locally

**Comment by anshul2401** [comment]
"args":["--flavor","dev"]
